reqAdmin/reqAdmin/urls.py
from django.conf.urls import patterns, include, url

from django.conf import settings

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'reqAdmin.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('reqApp.urls', namespace="reqApp")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': False}),
)

reqAdmin/reqApp/urls.py
from django.conf.urls import patterns, url

from reqApp import views

urlpatterns = patterns('',
    url(r'^$' , 'django.contrib.auth.views.login',
        {'template_name':'reqApp/index.html'}, name='login'),
    url(r'^logout/$' , 'django.contrib.auth.views.logout_then_login',
        name='logout'),

    url(r'^proyecto/$', views.selectProject, name='PR'),

    url(r'^proyecto/TU/$', views.viewTU, name='TU'),
    url(r'^proyecto/RU/$', views.viewRU, name='RU'),
    url(r'^proyecto/RS/$', views.viewRS, name='RS'),
    url(r'^proyecto/MD/$', views.viewMD, name='MD'),
    url(r'^proyecto/CP/$', views.viewCP, name='CP'),
    url(r'^proyecto/HT/$', views.viewHT, name='HT'),
    
    url(r'^documentos/requisitos/$', views.docRequisitos, name='docReq'),
    url(r'^documentos/diseno/$', views.docDiseno, name='docDis'),
    url(r'^documentos/casos_de_prueba/$', views.docCP, name='docCP'),
    url(r'^documentos/historico/$', views.docHistorico, name='docHis'),
    
    url(r'^herramientas/tareas/$', views.tareas, name='tareas'),
    url(r'^herramientas/estadisticas/$', views.estadisticas, name='estadisticas'),
    url(r'^herramientas/matrices/$', views.matrices, name='matrices'),
    url(r'^herramientas/consistencia/$', views.consistencia, name='consistencia'),
    url(r'^herramientas/bitacora/$', views.bitacora, name='bitacora'),
    
    url('^upload/img/$', views.imgUpload, name='mce_upload_image'),
    
    url(r'pdf/$', views.pdf, name='pdf'),
    
    url(r'^ayuda/$', views.help, name='help'),
)

reqAdmin/tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

try:
    from django.conf.urls import url, patterns
except:
    from django.conf.urls.defaults import url, patterns

urlpatterns = patterns('tinymce.views',
    url(r'^js/textareas/(?P<name>.+)/$', 'textareas_js', name='tinymce-js'),
    url(r'^js/textareas/(?P<name>.+)/(?P<lang>.*)$', 'textareas_js', name='tinymce-js-lang'),
    url(r'^spellchecker/$', 'spell_check'),
    url(r'^flatpages_link_list/$', 'flatpages_link_list'),
    url(r'^compressor/$', 'compressor', name='tinymce-compressor'),
    url(r'^filebrowser/$', 'filebrowser', name='tinymce-filebrowser'),
    url(r'^preview/(?P<name>.+)/$', 'preview', name='tinymce-preview'),
)

reqAdmin/templates/reqApp/herramientas/consistencia/consistencia.html
{% extends "reqApp/base.html" %}
{% load reqApp_tags %}
{% block body %}
<br/>
<div>
    <select style="display:inline-block;width:auto;vertical-align:top;" class="boton_azul" title="Seleccionar Relación de Consistencia" id='tipoSelect' onchange="location = this.options[this.selectedIndex].value;">
        {% for key,val in CONSISTENCIA_CHOICES %}
            <option value="?consistencia={{key}}"{% ifequal consistencia key %}selected{% endifequal %}>{{val}}</option>
        {% endfor %}
    </select>
    <select style="display:inline-block;width:auto;vertical-align:top;" class="boton_azul" title="Seleccionar Elemento" onchange="location = document.getElementById('tipoSelect').options[document.getElementById('tipoSelect').selectedIndex].value + this.options[this.selectedIndex].value;">
        {% for key,val in IDENTIFICADOR_CHOICES %}
            <option value="&identificador={{key}}"{% ifequal identificador|stringformat:"s" key|stringformat:"s" %}selected{% endifequal %}>{{val}}</option>
        {% endfor %}
    </select>
    <div style="display:inline-block;position:relative;float:right;">
        <a class="boton_azul" href="{% url 'reqApp:pdf' %}?tipo=CT&consistencia={{consistencia}}" target="_blank">PDF</a>
        <a title="Ayuda" class="boton_azul" href="{% url 'reqApp:help' %}#{{ helpLink }}" target="_blank">?</a>
    </div>
</div>
<br/>
<div>
<button title="útil para buscar (ctrl+f)" style="display: inline-block;width:auto;" href='#' class="boton_azul" onclick='abrirTodos()'>(+)Abrir Todos</button>
<button title="colapsar elementos" style="display: inline-block;width:auto;" href='#' class="boton_azul" onclick='cerrarTodos()'>(--)Cerrar Todos</button>
<div style="display: inline-block;width:20%;"></div>
</div>

<div style="text-align:right;">
    <div>
        <i style="color:Gray;">Colores: </i>
        <b class="cumple">cumple </b>
        <b class="no_cumple">no cumple </b>
        <b class="ambiguo">ambiguo </b>
    </div>
</div>

{% if atributos_ordenables %}
    {% with get_params="&consistencia="|concat:consistencia|concat:"&identificador="|concat:identificador %}
        {% include barra_orden_elementos with atributos=atributos_ordenables orden_actual=orden_actual getParams=get_params %}
    {% endwith %}
{% endif %}
    
{% ifequal elementos|length 0 %}
    <p class="centrado">--------------- Lista de Elementos Vacía ---------------</p>
{% else %}
    {% for e in elementos %}
        <div class="contenedorElemento">
            <div id="{{ e.elemento.textoIdentificador }}">
                {% include templates.elemento with elemento=e.elemento bitacora=False %}
            </div>
        </div>
        {% for se in e.subElementos %}
            <div style="margin-left:50px;" class="contenedorElemento">
                <div id="{{ se.textoIdentificador }}">
                    {% include templates.subElemento with elemento=se bitacora=False %}
                </div>
            </div>
        {% endfor %}
        <br/>
    {% endfor %}
{% endifequal %}

{% endblock %}