reqAdmin/reqAdmin/urls.py
from django.conf.urls import patterns, include, url

from django.conf import settings

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'reqAdmin.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('reqApp.urls', namespace="reqApp")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': False}),
)

reqAdmin/reqApp/urls.py
from django.conf.urls import patterns, url

from reqApp import views

urlpatterns = patterns('',
    url(r'^$' , 'django.contrib.auth.views.login',
        {'template_name':'reqApp/index.html'}, name='login'),
    url(r'^logout/$' , 'django.contrib.auth.views.logout_then_login',
        name='logout'),

    url(r'^proyecto/$', views.selectProject, name='PR'),

    url(r'^proyecto/TU/$', views.viewTU, name='TU'),
    url(r'^proyecto/RU/$', views.viewRU, name='RU'),
    url(r'^proyecto/RS/$', views.viewRS, name='RS'),
    url(r'^proyecto/MD/$', views.viewMD, name='MD'),
    url(r'^proyecto/CP/$', views.viewCP, name='CP'),
    url(r'^proyecto/HT/$', views.viewHT, name='HT'),
    
    url(r'^documentos/requisitos/$', views.docRequisitos, name='docReq'),
    url(r'^documentos/diseno/$', views.docDiseno, name='docDis'),
    url(r'^documentos/casos_de_prueba/$', views.docCP, name='docCP'),
    url(r'^documentos/historico/$', views.docHistorico, name='docHis'),
    
    url(r'^herramientas/tareas/$', views.tareas, name='tareas'),
    url(r'^herramientas/estadisticas/$', views.estadisticas, name='estadisticas'),
    url(r'^herramientas/matrices/$', views.matrices, name='matrices'),
    url(r'^herramientas/consistencia/$', views.consistencia, name='consistencia'),
    url(r'^herramientas/bitacora/$', views.bitacora, name='bitacora'),
    
    url('^upload/img/$', views.imgUpload, name='mce_upload_image'),
    
    url(r'pdf/$', views.pdf, name='pdf'),
    
    url(r'^ayuda/$', views.help, name='help'),
)

reqAdmin/tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

try:
    from django.conf.urls import url, patterns
except:
    from django.conf.urls.defaults import url, patterns

urlpatterns = patterns('tinymce.views',
    url(r'^js/textareas/(?P<name>.+)/$', 'textareas_js', name='tinymce-js'),
    url(r'^js/textareas/(?P<name>.+)/(?P<lang>.*)$', 'textareas_js', name='tinymce-js-lang'),
    url(r'^spellchecker/$', 'spell_check'),
    url(r'^flatpages_link_list/$', 'flatpages_link_list'),
    url(r'^compressor/$', 'compressor', name='tinymce-compressor'),
    url(r'^filebrowser/$', 'filebrowser', name='tinymce-filebrowser'),
    url(r'^preview/(?P<name>.+)/$', 'preview', name='tinymce-preview'),
)

reqAdmin/reqApp/views.py
# -*- encoding: utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from reqApp.forms import *
from reqApp.util import *
from django.contrib.auth.models import User
#from django.utils import simplejson
import json

from django.http import HttpResponse
from django.http import Http404

from django.db.models import Sum

################ after login ################
def selectProject(request):
    usuario = get_user_or_none(request) # TODO is None?
    if usuario is not None:
        if request.method == 'GET':
            if usuario.userprofile.proyectos.count() == 1:
                request.session['project'] = 0
            else:
                projects = []
                for i,p in enumerate(usuario.userprofile.proyectos.all().order_by('-id')):
                    projects.append((i,p))
                context = {
                    'projects':projects,
                }
                return render(request, 'reqApp/selectProject.html', context)
        else:
            if 'index' in request.POST:
                index = int(request.POST['index'])
                request.session['project'] = index
                print getProject(request)#checking
        return HttpResponseRedirect(reverse('reqApp:RU'))
    raise Http404

################ Elementos del Proyecto ################

def ajax_form_valid(form, validado):
    # para validar a traves de ajax
    if validado:
        response_dict = {'server_response': "OK" }
        return HttpResponse(json.dumps(response_dict), content_type='application/json')    
    else:
        errores = []
        for campo, errors in form.errors.items():
            for error in errors:
                errores.append([campo,error])
        response_dict = {'server_response': "FAIL", 'errores':errores}
        return HttpResponse(json.dumps(response_dict), content_type='application/json')

def elementView(request, mensajes, modelFormClass, elementTemplate, formTemplate, modelClass, navbar, pdfLink=None, helpLink=None):
    usuario = get_user_or_none(request) # TODO is None?
    proyecto = getProject(request)
    if request.method == 'POST':
        if 'identificador' in request.POST:# editar o borrar
            identificador = request.POST['identificador']
            instance = modelClass.objects.vigente(proyecto, identificador)
            if 'borrar' in request.POST:# borrar elemento
                instance.bitacorarElementoBorrado(usuario)
                mensajes.append(instance.textoIdentificador()+u' borrado y registrado en la bitácora')
            else:# editar elemento
                form = modelFormClass(instance=instance, data=request.POST)
                if form.is_valid():
                    if request.POST.has_key("solo_validar"):
                        return ajax_form_valid(form, True)
                    form.asignarProyecto(proyecto)
                    form.actualizarElementoDeBitacora(usuario, identificador)
                    mensajes.append(instance.textoIdentificador()+u' modificado y registrado en la bitácora')
                else:
                    if request.POST.has_key("solo_validar"):
                        return ajax_form_valid(form, False)
                    m=form.errors.as_text
                    mensajes.append('datos inválidos!')
                    mensajes.append(m)
        else:# crear
            form = modelFormClass(request.POST)
            if form.is_valid():
                if request.POST.has_key("solo_validar"):
                    return ajax_form_valid(form, True)
                form.asignarProyecto(proyecto)
                instance = form.crearElementoDeBitacora(usuario)
                mensajes.append(instance.textoIdentificador()+u' creado')
            else:
                if request.POST.has_key("solo_validar"):
                    return ajax_form_valid(form, False)
                mensajes.append('datos inválidos!')
    
    ordenActual = 'identificador'
    if 'orden' in request.GET:# ordenar lista de elementos
        ordenActual = request.GET['orden']
        elementos = modelClass.objects.vigentes(proyecto, ordenActual)
    else:
        elementos = modelClass.objects.vigentes(proyecto)
    
    listaElementos = []
    for elemento in elementos:
        listaElementos.append({'elemento':elemento, 'form':modelFormClass(instance=elemento).asignarProyecto(elemento.proyecto)})
    
    context = {
        'mensajes': mensajes,
        'elementos': listaElementos,
        'template':elementTemplate,
        'form': modelFormClass().asignarProyecto(proyecto),
        'form_template': formTemplate,
        'barra_orden_elementos': 'reqApp/orden_elementos.html',
        'atributos_ordenables': orderingList(modelClass),
        'orden_actual': ordenActual,
        'navbar':navbar,
        'pdfLink':pdfLink,
        'helpLink':helpLink,
        'canEdit':usuario.has_perm(u'reqApp.'+modelClass._meta.permissions[0][0]),
    }
    return render(request, 'reqApp/proyecto/lista_expandible.html', context)

def viewTU(request):
    mensajes = []
    navbar = {'1':'proyecto', '2':'TU'}
    return elementView(request, mensajes, TUForm, 'reqApp/proyecto/TU/TU.html', 'reqApp/proyecto/TU/TU_form.html', TipoUsuario, navbar, 'TU', 'TU')

def viewRU(request):
    mensajes = []
    navbar = {'1':'proyecto', '2':'RU'}
    return elementView(request, mensajes, RUForm, 'reqApp/proyecto/RU/RU.html', 'reqApp/proyecto/RU/RU_form.html', RequisitoUsuario, navbar, 'RU', 'RU')

def viewRS(request):
    mensajes = []
    navbar = {'1':'proyecto', '2':'RS'}
    return elementView(request, mensajes, RSForm, 'reqApp/proyecto/RS/RS.html', 'reqApp/proyecto/RS/RS_form.html', RequisitoSoftware, navbar, 'RS', 'RS')

def viewMD(request):
    mensajes = []
    navbar = {'1':'proyecto', '2':'MD'}
    return elementView(request, mensajes, MDForm, 'reqApp/proyecto/MD/MD.html', 'reqApp/proyecto/MD/MD_form.html', Modulo, navbar, 'MD', 'MD')

def viewCP(request):
    mensajes = []
    navbar = {'1':'proyecto', '2':'CP'}
    return elementView(request, mensajes, CPForm, 'reqApp/proyecto/CP/CP.html', 'reqApp/proyecto/CP/CP_form.html', CasoPrueba, navbar, 'CP', 'CP')
    
def viewHT(request):
    mensajes = []
    navbar = {'1':'proyecto', '2':'HT'}
    return elementView(request, mensajes, HTForm, 'reqApp/proyecto/HT/HT.html', 'reqApp/proyecto/HT/HT_form.html', Hito, navbar, 'HT', 'HT')
    
################################# Documentos #############################
def docView(request, navbar, activos, pdfLink, helpLink=None):
    usuario = get_user_or_none(request) # TODO is None?
    proyecto = getProject(request)

    parrafo =  request.GET.get('parrafo', activos[0]) # valor por defecto si no corresponde a ningun tipo de parrafo conocido
    if parrafo not in activos:
        parrafo = activos[0]
        
    parrafos = []
    for pa in PARRAFOS_CHOICES:
        activo = False
        if pa[0] in activos:
            activo = True
        parrafos.append({'tipo':pa[0], 'nombre':pa[1], 'activo':activo})
    
    context = {
        'navbar':navbar,
        'parrafos':parrafos,
        'parrafo':parrafo,
        'pdfLink':pdfLink,
        'helpLink':helpLink,
    }
    
    id_version = -1 # sin version seleccionada para edición
    if request.method == 'POST':
        form = DocForm(request.POST)
        if form.is_valid():
            form.registrarDocumento(proyecto, usuario, parrafo) # guardar cambios
    elif request.method == 'GET':
        id_version =  int(request.GET.get('id', -1))# version seleccionada para edición
    
    versiones = Documento.objects.versiones(proyecto, parrafo, 10)# solo se muestran las ultimas 10 versiones de la sección/párrafo (<0 para mostrar todas)
    if len(versiones) > 0:
        vigente = versiones[0]
        context.update({'vigente':vigente,'versiones':versiones})
        
        if id_version >= 0: # si desea obtener una version en particular
            version = None
            for vers in versiones:
                if vers.id == id_version:
                    version = vers
                    break
                
            if version is not None: # si la version solicitada está presente en las versiones consideradas aquí
                form = DocForm(instance=version) # cargamos el editor mce con la versión solicitada
                context.update({'id_version':id_version})
            else: # si no se encontró la versión solocitada
                form = DocForm(instance=vigente) # se carga la versión actual (vigente)
        else:
            form = DocForm(instance=vigente) # se carga la versión actual (vigente)
    else:
        form = DocForm() # si no hay versiones registradas anteriormente para esta sección/párrafo
        
    context.update({'form':form,})
    
    
    return render(request, 'reqApp/documentos/documentos.html', context)

def docRequisitos(request):
    navbar = {'1':'documentos', '2':'requisitos'}
    parrafos = [
        'introduccion',
        'proposito',
        'alcance',
        'contexto',
        'definiciones',
        'referencias',
        'descripcion_general',
        
        'usuarios',
        'producto',
        'ambiente',
        'proyectos_relacionados',
    ]
    return docView(request, navbar, parrafos, 'docReq', 'docReq')
    
def docDiseno(request):
    navbar = {'1':'documentos', '2':'diseno'}
    parrafos = [
        'introduccion',
        'proposito',
        'alcance',
        'contexto',
        'definiciones',
        'referencias',
        'descripcion_general',
        
        'diseno',
        'arquitectura_fisica',
        'arquitectura_logica',
        'modelo',
        'detalle_modulos',
        'navegacion',
        'interfaz',
    ]
    return docView(request, navbar, parrafos, 'docDis', 'docDis')
    
def docCP(request):
    navbar = {'1':'documentos', '2':'cp'}
    parrafos = [
        'introduccion',
        'proposito',
        'alcance',

reqAdmin/templates/reqApp/base.html
{% load staticfiles %}
{% load reqApp_tags %}

<!DOCTYPE html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reqApp.css' %}" />
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'js/reqApp.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.dropdown.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.dropdown.css' %}" />
    
    <title>mainReq</title>
</head>

<body>
    <div class="userDropDown">
        <span data-dropdown="#dropdown-1">{{user}}</span>
    </div>
    
    {% include "reqApp/navbar.html" with proyecto=request|proyecto %}
    
    {% block body %}{% endblock %}
    
    <div id="dropdown-1" class="dropdown dropdown-tip dropdown-anchor-right">
        <div style="text-align:center;" class="contenedorElemento">
            <div>{{user.first_name}} {{user.last_name}}</div>
            <div>{{user.email}}</div>
            <a href="{% url 'reqApp:logout' %}">Salir</a>
        </div>
    </div>
</body>
</html>

reqAdmin/templates/reqApp/help.html
{% load staticfiles %}
<!DOCTYPE html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reqApp.css' %}" />
    <title>mainReq::ayuda</title>
</head>

<body>
    <h1>MainReq: Definiciones y Preguntas Frecuentes</h1>
    <br/>
    <br/>
    <h2><a name="HT">Hitos: HT</a></h2>
    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
    <h2><a name="TU">Tipos de Usuario: TU</a></h2>
    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
    <h2><a name="RU">Requisitos de Usuario: RU</a></h2>
    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
    <h2><a name="RS">Requisitos de Software: RS</a></h2>
    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
    <h2><a name="MD">Mósulos: MD</a></h2>
    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
    <h2><a name="CP">Casos de Prueba: CP</a></h2>
    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
    <h2><a name="docReq">Documento de Requisitos</a></h2>
    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
    <h2><a name="docDis">Documento de Diseño</a></h2>
    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
    <h2><a name="docCP">Documento de Casos de Prueba</a></h2>
    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
    <h2><a name="docHis">Documento Histórico</a></h2>
    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
    <h2><a name="task">Tareas</a></h2>
    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
    <h2><a name="ET">Estadísticas del Proyecto</a></h2>
    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
    <h2><a name="matrix">Matrices de Trazado</a></h2>
    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
    <h2><a name="cons">Consistencia de Relaciones</a></h2>
    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
    <h2><a name="reg">Bitácora de Elementos del Proyecto</a></h2>
    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
</body>
</html>

reqAdmin/templates/reqApp/index.html
{% load staticfiles %}
<!DOCTYPE html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reqApp.css' %}" />
    <title>mainReq</title>
</head>

<body>
    <div style="text-align:center;padding:10px" class="contenedorElemento">
        <h1><i>main</i><span><a style="color:Black;text-decoration:none;cursor:text;" href="{% url 'admin:index' %}">R</a><span>eq</h1>
        <form method="POST">{% csrf_token %}
            {% if form.non_field_errors %}
                <p class="invalido">Contraseña o Usuario incorrecto!</p>
            {% elif form.errors %}
                <p class="invalido">Contraseña o Usuario incorrecto!</p>
            {% endif %}
            <div>
                <input name="username" type="text" id="user" placeholder="Usuario">
            </div>

            <div>
                <input name="password" type="password" id="inputPassword" placeholder="Contraseña">
            </div>
            <br/>
            <button class="boton_azul" type="submit">Ingresar</button>
        </form>
    </div>
</body>
</html>

reqAdmin/templates/reqApp/navbar.html
{# espera variable: proyecto #}
<script>
$(document).ready(function() {
    $('.userDropDown').dropit();
});
</script>

<div class="navbar_up">
    <ul>
    <li><a title="Editar/Ver Elementos&#013;del Proyecto" name="navbar" {% ifequal navbar.1 "proyecto" %} class="navbar_selected" {% endifequal %} href="{% url 'reqApp:RU' %}">Proyecto</a></li>
    <li><a title="Editar/Descargar Documentos&#013;del Proyecto" name="navbar" {% ifequal navbar.1 "documentos" %} class="navbar_selected" {% endifequal %} href="{% url 'reqApp:docReq' %}">Documentos</a></li>
    <li><a title="Tareas,&#013;Estadísticas,&#013;Matrices,&#013;Consistencia,&#013;Bitácora" name="navbar" {% ifequal navbar.1 "herramientas" %} class="navbar_selected" {% endifequal %} href="{% url 'reqApp:tareas' %}">Herramientas</a></li>
    </ul>
</div>

<div class="proyect_name">
<p>{{ proyecto }}</p>
</div>
<div class="navbar_down">
    <ul>
        {% ifequal navbar.1 "proyecto" %}
            <li><a title="HT" name="navbar" {% ifequal navbar.2 "HT" %} class="navbar_selected" {% endifequal %} href="{% url 'reqApp:HT' %}">Hitos</a></li>
            <li><a title="TU" name="navbar" {% ifequal navbar.2 "TU" %} class="navbar_selected" {% endifequal %} href="{% url 'reqApp:TU' %}">Tipos de Usuario</a></li>
            <li><a title="RU" name="navbar" {% ifequal navbar.2 "RU" %} class="navbar_selected" {% endifequal %} href="{% url 'reqApp:RU' %}">Requisitos de Usuario</a></li>
            <li><a title="RS" name="navbar" {% ifequal navbar.2 "RS" %} class="navbar_selected" {% endifequal %} href="{% url 'reqApp:RS' %}">Requisitos de Software</a></li>
            <li><a title="MD" name="navbar" {% ifequal navbar.2 "MD" %} class="navbar_selected" {% endifequal %} href="{% url 'reqApp:MD' %}">Módulos</a></li>
            <li><a title="CP" name="navbar" {% ifequal navbar.2 "CP" %} class="navbar_selected" {% endifequal %} href="{% url 'reqApp:CP' %}">Casos de Prueba</a></li>
        {% endifequal %}
        
        {% ifequal navbar.1 "documentos" %}
            <li><a title="Editar/Descargar Documento&#013;de Requisitos" name="navbar" {% ifequal navbar.2 "requisitos" %} class="navbar_selected" {% endifequal %} href="{% url 'reqApp:docReq' %}">Documento de Requisitos</a></li>
            <li><a title="Editar/Descargar Documento&#013;de Diseño" name="navbar" {% ifequal navbar.2 "diseno" %} class="navbar_selected" {% endifequal %} href="{% url 'reqApp:docDis' %}">Documento de Diseño</a></li>
            <li><a title="Editar/Descargar Documento&#013;de Casos de Prueba" name="navbar" {% ifequal navbar.2 "cp" %} class="navbar_selected" {% endifequal %} href="{% url 'reqApp:docCP' %}">Documento de Casos de Prueba</a></li>
            <li><a title="Editar/Descargar Documento&#013;Histórico" name="navbar" {% ifequal navbar.2 "historico" %} class="navbar_selected" {% endifequal %} href="{% url 'reqApp:docHis' %}">Documento Histórico</a></li>
        {% endifequal %}
        
        {% ifequal navbar.1 "herramientas" %}
            <li><a title="Reportar/Asignar&#013;Tareas Individuales" name="navbar" {% ifequal navbar.2 "tareas" %} class="navbar_selected" {% endifequal %} href="{% url 'reqApp:tareas' %}">Tareas</a></li>
            <li><a title="Indicadores Estadísticos&#013;de Avance del Proyecto&#013;por Hito" name="navbar" {% ifequal navbar.2 "estadisticas" %} class="navbar_selected" {% endifequal %} href="{% url 'reqApp:estadisticas' %}">Estadísticas</a></li>
            <li><a title="Matrices de Trazado" name="navbar" {% ifequal navbar.2 "matrices" %} class="navbar_selected" {% endifequal %} href="{% url 'reqApp:matrices' %}">Matrices de Trazado</a></li>
            <li><a title="Revisar la Consistencia&#013;de Relaciones entre&#013;Elementos del Proyecto" name="navbar" {% ifequal navbar.2 "consistencia" %} class="navbar_selected" {% endifequal %} href="{% url 'reqApp:consistencia' %}">Consistencia de Relaciones</a></li>
            <li><a title="Historial de Cambios&#013;de Elementos del Proyecto" name="navbar" {% ifequal navbar.2 "bitacora" %} class="navbar_selected" {% endifequal %} href="{% url 'reqApp:bitacora' %}">Bitácora</a></li>
        {% endifequal %}
    </ul>
</div>

reqAdmin/templates/reqApp/orden_elementos.html
{% load reqApp_tags %}
<div class="barra_orden">
{% for atributo in atributos %}
    <div style="display: inline-block;width:{{ atributo.posicion }}%;">
        {% ifequal orden_actual atributo.orden %}
            <a class="barra_orden" href='?orden=-{{ atributo.orden }}{{getParams}}'><b>{{ atributo.orden }}</b></a>
        {% else %}
            {% ifequal orden_actual atributo.orden|invertOrd %}
                <a class="barra_orden" href='?orden={{ atributo.orden }}{{getParams}}'><b>{{ atributo.orden }}</b></a>
            {% else %}
                <a class="barra_orden" href='?orden={{ atributo.orden }}{{getParams}}'>{{ atributo.orden }}</a>
            {% endifequal %}
        {% endifequal %}
    </div>
{% endfor %}
</div>

reqAdmin/templates/reqApp/selectProject.html
{% load staticfiles %}
<!DOCTYPE html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reqApp.css' %}" />
    <title>mainReq</title>
</head>

<body>
    <div style="text-align:center;padding:10px" class="contenedorElemento">
        <h1><i>main</i>Req</h1>
        <h2>Hola {{user}}</h2>
        {% if projects %}
            <form method="POST">{% csrf_token %}
                <div style="text-align:left">
                    <p>Selecciona un proyecto:</p>
                    {% for index,pr in projects %}
                        <input style="cursor:pointer" id="{{index}}" type="radio" name="index" value="{{index}}" onchange="this.form.submit()">
                            <label style="cursor:pointer;" onMouseOver="this.style.color='#00F'" onMouseOut="this.style.color='#000'" for="{{index}}"><b>{{pr}}</b></label>
                        <div style="margin-left:50px;">{{pr.descripcion}}</div>
                    {% endfor %}
                </div>
            </form>
        {% else %}
            <p>!No tiene proyectos asociados!</p>
        {% endif %}
        <br/>
        <a class="boton_azul" href="{% url 'reqApp:logout' %}">Salir</a>
    </div>
</body>
</html>